spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.1
          zkNodes: 192.168.99.1
      default-binder: kafka

stubrunner:
  stubsMode: REMOTE
  repositoryRoot: http://localhost:8081/artifactory/libs-release-local # Is sent by pipeline

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-school:8761/eureka/