management:
  endpoints:
    web.base-path: /

server:
  port: 8765

stubrunner:
  cloud:
    stubbed:
      discovery:
        enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

