spring:
  application:
    name: classcustomerstubrunnerschool
  profiles:
    active: development

server:
  port: 8050

management:
  endpoints:
    web.base-path: /

stubrunner:
  cloud:
    stubbed:
      discovery:
        enabled: false

---

spring:
  profiles: development

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost
      default-binder: kafka

stubrunner:
  stubsMode: LOCAL
  ids:
    - com.elipcero.classcustomerschool:classcustomer-school:+:stubs:8762

---

spring:
  profiles: kubernetes

  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.1
          zkNodes: 192.168.99.1
      default-binder: kafka